server:
  port: 8081

spring:

  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/RegistrationDB
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  jwt:
    secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMDkwNjM1NiwiaWF0IjoxNzIwOTA2MzU2fQ.ySGypfDwu-jrAbhZGEh6fUO-dg3iXJX5FYP2RqdDSj0
    expirationMs: 3600000




